= Integration Blueprint
:proj-name: integration_blueprint
:gh-name: ludeeus/{proj-name}
:badge-style: flat-square

image:https://img.shields.io/github/release/{gh-name}.svg?style={badge-style}[GitHub Release, link=https://github.com/{gh-name}/releases]

_Integration to integrate with ...._

*This integration will set up the following platforms.*

|===
| Platform        | Description

| `binary_sensor` | Show something `True` or `False`.
| `sensor`        | Show info from blueprint API.
| `switch`        | Switch something `True` or `False`.
|===


== Installation

. Using the tool of choice open the directory (folder) for your HA configuration (where you find `configuration.yaml`).
. If you do not have a `custom_components` directory (folder) there, you need to create it.
. In the `custom_components` directory (folder) create a new folder called `{proj-name}`.
. Download _all_ the files from the `custom_components/{proj-name}/` directory (folder) in this repository.
. Place the files you downloaded in the new directory (folder) you created.
. Restart Home Assistant
. In the HA UI go to “Configuration” -> “Integrations” click “+” and search for “Integration Blueprint”
