name: Lint

on:
  - push
  - pull_request

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: 3.12
            cache: pip

        - name: Install requirements
          run: python3 -m pip install -r requirements.txt

        - name: Check code-style
          run: python3 -m ruff check .

  typechecker:
    name: Typechecker
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: 3.12
            cache: pip

        - name: Install requirements
          run: python3 -m pip install -r requirements.txt

        - name: Check types
          run: basedpyright
