name: Lint

on:
  - push
  - pull_request

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: 3.11
            cache: pip

        - name: Install requirements
          run: python3 -m pip install -r requirements.txt

        - name: Check types
          run: basedpyright

        - name: Check code-style
          run: python3 -m ruff check .
