name: Release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Adjust version number
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            custom_components/smarwi/manifest.json

      - name: ZIP the integration directory
        run: zip smarwi.zip -r ./
        working-directory: custom_components/smarwi

      - name: Upload the ZIP file to the release
        uses: softprops/action-gh-release@v2
        with:
          files: custom_components/smarwi/smarwi.zip
