name: Validate

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # https://developers.home-assistant.io/blog/2020/04/16/hassfest
  hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master

  # https://github.com/hacs/action
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration
          # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
          ignore: brands
